ERROR | 2022-10-09 22:57:40,684 | main.py:37 | BOT WAS STARTED
NoneType: None
ERROR | 2022-10-09 22:58:15,819 | z_all_errors.py:21 | Exception: list index out of range
Update: {"update_id": 46689274, "callback_query": {"id": "4134613427737649936", "from": {"id": 962664705, "is_bot": false, "first_name": "Heisenbergᅠࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣧࣧࣧࣧࣧࣧࣧࣧࣧࣧࣧᅠᅠࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣧࣧࣧࣧࣧࣧࣧࣧࣧࣧࣧ", "username": "nniIkon", "language_code": "en"}, "message": {"message_id": 2570, "from": {"id": 5366267602, "is_bot": true, "first_name": "eBilim", "username": "ebilim_bot"}, "chat": {"id": 962664705, "first_name": "Heisenbergᅠࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣧࣧࣧࣧࣧࣧࣧࣧࣧࣧࣧᅠᅠࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣧࣧࣧࣧࣧࣧࣧࣧࣧࣧࣧ", "username": "nniIkon", "type": "private"}, "date": 1665334427, "edit_date": 1665334690, "text": "Предметы", "reply_markup": {"inline_keyboard": [[{"text": "Базы данных 1 н/у", "callback_data": "/StudentJurnal/course?planId=314&year=22&session=1&idDis=15"}], [{"text": "Прикладная математика н/у", "callback_data": "/StudentJurnal/course?planId=430&year=22&session=1&idDis=14"}], [{"text": "Языки программирования 3 н/у", "callback_data": "/StudentJurnal/course?planId=431&year=22&session=1&idDis=16"}], [{"text": "Компьютерные сети и телекоммуникации н/у", "callback_data": "/StudentJurnal/course?planId=432&year=22&session=1&idDis=26"}], [{"text": "Немецкий язык 3 н/у", "callback_data": "/StudentJurnal/course?planId=433&year=22&session=1&idDis=18"}], [{"text": "Веб-технологии н/у", "callback_data": "/StudentJurnal/course?planId=434&year=22&session=1&idDis=36"}], [{"text": "Языки программирования 3 -", "callback_data": "/StudentJurnal/course?planId=442&year=22&session=1&idDis=16"}]]}}, "chat_instance": "3012313766790908771", "data": "/StudentJurnal/course?planId=431&year=22&session=1&idDis=16"}}
Traceback (most recent call last):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/handlers/user.py", line 198, in insert_login
    text = f"Оценки по предмету: <code>{subject[14]}</code>\n" \
IndexError: list index out of range
ERROR | 2022-10-09 22:58:15,820 | base_events.py:1744 | Task exception was never retrieved
future: <Task finished name='Task-25' coro=<Dispatcher._process_polling_updates() done, defined at /home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/handlers/user.py", line 198, in insert_login
    text = f"Оценки по предмету: <code>{subject[14]}</code>\n" \
IndexError: list index out of range
ERROR | 2022-10-09 22:59:21,495 | z_all_errors.py:21 | Exception: list index out of range
Update: {"update_id": 46689281, "callback_query": {"id": "4134613426825076744", "from": {"id": 962664705, "is_bot": false, "first_name": "Heisenbergᅠࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣧࣧࣧࣧࣧࣧࣧࣧࣧࣧࣧᅠᅠࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣧࣧࣧࣧࣧࣧࣧࣧࣧࣧࣧ", "username": "nniIkon", "language_code": "en"}, "message": {"message_id": 2570, "from": {"id": 5366267602, "is_bot": true, "first_name": "eBilim", "username": "ebilim_bot"}, "chat": {"id": 962664705, "first_name": "Heisenbergᅠࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣧࣧࣧࣧࣧࣧࣧࣧࣧࣧࣧᅠᅠࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣩࣧࣧࣧࣧࣧࣧࣧࣧࣧࣧࣧ", "username": "nniIkon", "type": "private"}, "date": 1665334427, "edit_date": 1665334749, "text": "Предметы", "reply_markup": {"inline_keyboard": [[{"text": "Базы данных 1 н/у", "callback_data": "/StudentJurnal/course?planId=314&year=22&session=1&idDis=15"}], [{"text": "Прикладная математика н/у", "callback_data": "/StudentJurnal/course?planId=430&year=22&session=1&idDis=14"}], [{"text": "Языки программирования 3 н/у", "callback_data": "/StudentJurnal/course?planId=431&year=22&session=1&idDis=16"}], [{"text": "Компьютерные сети и телекоммуникации н/у", "callback_data": "/StudentJurnal/course?planId=432&year=22&session=1&idDis=26"}], [{"text": "Немецкий язык 3 н/у", "callback_data": "/StudentJurnal/course?planId=433&year=22&session=1&idDis=18"}], [{"text": "Веб-технологии н/у", "callback_data": "/StudentJurnal/course?planId=434&year=22&session=1&idDis=36"}], [{"text": "Языки программирования 3 -", "callback_data": "/StudentJurnal/course?planId=442&year=22&session=1&idDis=16"}]]}}, "chat_instance": "3012313766790908771", "data": "/StudentJurnal/course?planId=442&year=22&session=1&idDis=16"}}
Traceback (most recent call last):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/handlers/user.py", line 198, in insert_login
    text = f"Оценки по предмету: <code>{subject[14]}</code>\n" \
IndexError: list index out of range
ERROR | 2022-10-09 22:59:21,495 | base_events.py:1744 | Task exception was never retrieved
future: <Task finished name='Task-53' coro=<Dispatcher._process_polling_updates() done, defined at /home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/handlers/user.py", line 198, in insert_login
    text = f"Оценки по предмету: <code>{subject[14]}</code>\n" \
IndexError: list index out of range
WARNING | 2022-10-09 22:59:27,401 | executor.py:329 | Goodbye!
